### ISSUE TITLE
Didn't see stars

### ISSUE THREAD

**Issue by cryptofuture** [NovakDistributed/macroverse-website#1]
I have no twitter account, and didn't found how to contact you.
![macroverse](https://user-images.githubusercontent.com/6484506/27769214-d0b12948-5f14-11e7-9c3c-e0ad8462f8a2.jpg)
Basically, when I use metamask in firefox, I didn't see my MRV balance, I think this is because no token support in firefox metamask, yet.
But in chromium looks like it works and I see MRV balance, but still blank picture. 
I have no idea on what stage you right now, but from your twitter picture and entires, I pretend I should see universe with planets weights and etc.
Also, I think later you can just pack browser client (like electron or nw.js) with all requirements to make it easier to use.

**Comment by interfect** [comment]
It looks like maybe your browser isn't doing WebGL. There are definitely
supposed to be stars in that white box; planets unfortunately haven't been
implemented yet.

What results do you get if you use http://webglreport.com/ to inspect your
browser's WebGL configuration? You might also want to inspect chrome://gpu/
to see if Chromium is happy with the GPU and its drivers.

Can you see the 3D spaceship in https://www.babylonjs.com/demos/spaceship/
or does it not load?

I'll think about packaging the explorer up as a standalone binary. It would
somehow need to access your Ethereum node, but maybe it could work like
Mist does.

I didn't know MetaMask existed for Firefox. I've just gone and tested it
now, and it dies with some internal error in MetaMask, but it does start up
WebGL and draw a green wireframe cube on a black background. When you
loaded the page in Firefox, did you at least get the 3D wireframe cube on
the black background? Or did you also get no 3D output?

**Comment by cryptofuture** [comment]
Thanks. It works!
![macroverse2](https://user-images.githubusercontent.com/6484506/27781473-871e4398-5fbd-11e7-864a-0254f9c221bf.jpg)
`chrome://gpu/` showed that only webgl1 supported, but webgl2 disabled.
Per https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser I activated `Override software rendering list` in `chrome://flags` and it works now.
Looks like webgl2 is disabled for most Linux users by default. And I think you can add basic webgl support detection, to display error message.
I think with some metamask update (tokens tab) it could be workable in firefox too.
